# -*- coding: utf-8 -*-
"""RBAT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/MPicc/ProgettoDPP/blob/main/RBAT.ipynb
"""

!pip install spmf

from google.colab import drive
drive.mount('/content/drive')

from spmf import Spmf

spmf = Spmf("PrefixSpan", input_filename="/content/drive/MyDrive/ProgettoDPP/BMS1_spmf.txt",
            output_filename="output.txt", arguments=[0.7, 5])
spmf.run()
print(spmf.to_pandas_dataframe(pickle=True))
spmf.to_csv("output.csv")

a = 2